
<?php

/* 
 * Simple parser for DATABASE_URL in PHP 
 */
if (getenv('DATABASE_URL')) {
  $url = parse_url(getenv("DATABASE_URL"));

  putenv('DB_CONNECTION=' . ($url['scheme'] == 'postgres' ? 'pgsql' : $url['scheme']));
  putenv("DB_HOST={$url['host']}");
  putenv("DB_PORT={$url['port']}");
  putenv("DB_USERNAME={$url['user']}");
  putenv("DB_PASSWORD={$url['pass']}");
  putenv('DB_DATABASE=' . substr($url['path'], 1)); // Remove leading slash from path
}

/*
 * Define Wordpress configuration 
 */
define('DB_NAME', getenv('DB_DATABASE'));

/** MySQL database username */
define('DB_USER', getenv('DB_USERNAME'));

/** MySQL database password */
define('DB_PASSWORD', getenv('DB_PASSWORD'));

/** MySQL hostname */
define('DB_HOST', getenv('DB_HOST'));

/*
 * Keys generated by https://api.wordpress.org/secret-key/1.1/salt/ for this project 
 */
define('AUTH_KEY',         'V<dD(+NN/JJ^FvcEB*&Hbd$1TC[2,xx05773+|KE#[3oqC/3~os R,Tv+7-0KMVR');
define('SECURE_AUTH_KEY',  'QPTW$j_}fJ&SqY}x*v.FeAHrz<IzM*Lxi`2[,``hbUc,SNB1~4^syx?^Cz]E5!d1');
define('LOGGED_IN_KEY',    '!ecTcG[4RWhMIXOY=?KyD/1A+)!K(Zc)|8CAxTj|oae+`x-kfhB@f&VklX!{n7nj');
define('NONCE_KEY',        '@uYY-|GT`5d>eGA0/<yi^ddn->JvhnzUygrFi{a+.DbG-(bmt8ZwF%/i:w}~rCWx');
define('AUTH_SALT',        'R$xJp--f@sGvvq&- `3z*+4vu2mKl|*m!H`i*lP&@,Izrv;x}?DYeoh8,dp+2xM.');
define('SECURE_AUTH_SALT', 'm*BU!$/Du-4n!>)Q++>GQ&sO;|^]2I_7E93l]AH+&{PF/Mlc%e8Px;ZS+<q=@fZ/');
define('LOGGED_IN_SALT',   'VDnv3-4i?|e`Nml|VkVJ+arNVqrN;>^~lop+M&=ZFyZ|V<hy#-}3g|;sQD++<yD}');
define('NONCE_SALT',       'd,lJ(-`i<1Kb&red<Rj1E]]HAr.ozkf9|#&BL;j#x,Y#/F[uy}2e-f.G|W}rLkJt');

?>
